// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from helloworld.djinni

#import "DCHelloWorld+Private.h"
#import "DCHelloWorld.h"
#import "DCHelloWorld+Private.h"
#import "djinni/support-lib/objc/DJICppWrapperCache+Private.h"
#import "djinni/support-lib/objc/DJIError.h"
#import "djinni/support-lib/objc/DJIMarshal+Private.h"
#include <exception>
#include <utility>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@interface DCHelloWorld ()

- (id)initWithCpp:(const std::shared_ptr<::djinnicmakeexample::HelloWorld>&)cppRef;

@end

@implementation DCHelloWorld {
    ::djinni::CppProxyCache::Handle<std::shared_ptr<::djinnicmakeexample::HelloWorld>> _cppRefHandle;
}

- (id)initWithCpp:(const std::shared_ptr<::djinnicmakeexample::HelloWorld>&)cppRef
{
    if (self = [super init]) {
        _cppRefHandle.assign(cppRef);
    }
    return self;
}

+ (nullable DCHelloWorld *)create {
    try {
        auto r = ::djinnicmakeexample::HelloWorld::create();
        return ::djinni_generated::HelloWorld::fromCpp(r);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

- (nonnull NSString *)getHelloString {
    try {
        auto r = _cppRefHandle.get()->getHelloString();
        return ::djinni::String::fromCpp(r);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

namespace djinni_generated {

auto HelloWorld::toCpp(ObjcType objc) -> CppType
{
    if (!objc) {
        return nullptr;
    }
    return objc->_cppRefHandle.get();
}

auto HelloWorld::fromCppOpt(const CppOptType& cpp) -> ObjcType
{
    if (!cpp) {
        return nil;
    }
    return ::djinni::get_cpp_proxy<DCHelloWorld>(cpp);
}

}  // namespace djinni_generated

@end
