// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from helloworld.djinni

#import <Foundation/Foundation.h>
@class DCHelloWorld;


@interface DCHelloWorld : NSObject

+ (nullable DCHelloWorld *)create;

- (nonnull NSString *)getHelloString;

@end
